#!/usr/bin/env sh
. "$(dirname -- "$0")/_/h"

echo "husky - pre-commit hook running..."

npm run build || exit 1
npm run benchmark -- --runs 3 --warmup 1 || exit 1

git add bench/results/benchmarks.json